name = "linkedin-company-intern"
compatibility_date = "2025-03-28"
main = "src/index.js"
account_id = "46827c91abf2fd46f0c180ba88207593"
workers_dev = true

[triggers]
crons = []

[observability.logs]
enabled = true




